### ISSUE TITLE
Application not showing translations when language is forced to English

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton-mobile#19]
The translation system seems to be working only with Brazilian Portuguese.

When we try to use other language (like English), it does not work.

Steps to reproduce:
1. In XCode, go to menu Product -> Scheme -> Edit scheme
2. In App Language, select English:
![image](https://user-images.githubusercontent.com/2075267/163004854-ed335a49-f77c-4476-936d-325a47f1bada.png)
3. Run the application.

Current result:
![image](https://user-images.githubusercontent.com/2075267/163010672-0372a04f-6416-4cfb-8b96-a79a6d5ce828.png)

Expected result:
Application should show the translations in english;

PS: the fallback language must be English

**Comment by gustavo-em** [comment]
Pull Request 
#21

**Comment by gustavo-em** [comment]
Test link PR in issue #22
