### ISSUE TITLE
Ipad layout not using the whole screen device

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton-mobile#20]
When this application runs in iPad, the application is small (not using the whole screen).

Steps to reproduce:
1. Run the application using ipad in device simulator

Expected result:
Application should use the entire screen.

Current result:
![image](https://user-images.githubusercontent.com/2075267/163005678-36cde683-8c39-43cc-87af-6886e1d215af.png)

**Comment by gustavo-em** [comment]
PR #28
