### ISSUE TITLE
Unable to share screen on Android 

### ISSUE THREAD

**Issue by rabiea** [bigbluebutton/bigbluebutton-mobile#54]
I am unable to share screen using android

 LOG  handleWebviewMessage -  1
 LOG  [1] - >nativeInitializeScreenShare
 ERROR  [1] - Promise 1 failed! Call to nativeInitializeScreenShare failed zzy
 LOG  handleWebviewMessage -  1

**Comment by TiagoJacobs** [comment]
hello @rabiea - thank you very much for this post.

This looks duplicate of https://github.com/bigbluebutton/bigbluebutton-tablet/issues/52, as there is no implementation for Android yet.

Closing it for now.
